### ISSUE TITLE
[Environmental configuration] Installation of frnn

### ISSUE THREAD

**Issue by MenglinQiu** [lxxue/FRNN#12]
Hi, lixin Xue:
I have some problems installing frnn, can you give me some advice to solve these problems?  thanks for your help!

`
Processing /media/shi/projects/FRNN/external/prefix_sum
Preparing metadata (setup.py) ... done
Building wheels for collected packages: prefix-sum
Building wheel for prefix-sum (setup.py) ... error
error: subprocess-exited-with-error

× python setup.py bdist_wheel did not run successfully.
│ exit code: 1
╰─> [53 lines of output]
running bdist_wheel
running build
running build_ext
Traceback (most recent call last):
File "", line 2, in
File "", line 34, in
File "/media/shi/projects/FRNN/external/prefix_sum/setup.py", line 9, in
setup(
File "/home/shi/anaconda3/envs/frnn/lib/python3.8/site-packages/setuptools/init.py", line 107, in setup
return distutils.core.setup(**attrs)
File "/home/shi/anaconda3/envs/frnn/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
return run_commands(dist)
File "/home/shi/anaconda3/envs/frnn/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
dist.run_commands()
File "/home/shi/anaconda3/envs/frnn/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
self.run_command(cmd)
File "/home/shi/anaconda3/envs/frnn/lib/python3.8/site-packages/setuptools/dist.py", line 1234, in run_command
super().run_command(command)
File "/home/shi/anaconda3/envs/frnn/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
cmd_obj.run()
File "/home/shi/anaconda3/envs/frnn/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 325, in run
self.run_command("build")
File "/home/shi/anaconda3/envs/frnn/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
self.distribution.run_command(command)
File "/home/shi/anaconda3/envs/frnn/lib/python3.8/site-packages/setuptools/dist.py", line 1234, in run_command
super().run_command(command)
File "/home/shi/anaconda3/envs/frnn/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
cmd_obj.run()
File "/home/shi/anaconda3/envs/frnn/lib/python3.8/site-packages/setuptools/_distutils/command/build.py", line 131, in run
self.run_command(cmd_name)
File "/home/shi/anaconda3/envs/frnn/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
self.distribution.run_command(command)
File "/home/shi/anaconda3/envs/frnn/lib/python3.8/site-packages/setuptools/dist.py", line 1234, in run_command
super().run_command(command)
File "/home/shi/anaconda3/envs/frnn/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
cmd_obj.run()
File "/home/shi/anaconda3/envs/frnn/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 84, in run
_build_ext.run(self)
File "/home/shi/anaconda3/envs/frnn/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
self.build_extensions()
File "/home/shi/anaconda3/envs/frnn/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 390, in build_extensions
self._check_abi()
File "/home/shi/anaconda3/envs/frnn/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 761, in _check_abi
check_compiler_abi_compatibility(compiler)
File "/home/shi/anaconda3/envs/frnn/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 294, in check_compiler_abi_compatibility
if not check_compiler_ok_for_platform(compiler):
File "/home/shi/anaconda3/envs/frnn/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 254, in check_compiler_ok_for_platform
which = subprocess.check_output(['which', compiler], stderr=subprocess.STDOUT)
File "/home/shi/anaconda3/envs/frnn/lib/python3.8/subprocess.py", line 415, in check_output
return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
File "/home/shi/anaconda3/envs/frnn/lib/python3.8/subprocess.py", line 516, in run
raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['which', 'g++']' returned non-zero exit status 1.
[end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
ERROR: Failed building wheel for prefix-sum
Running setup.py clean for prefix-sum
Failed to build prefix-sum
ERROR: Could not build wheels for prefix-sum, which is required to install pyproject.toml-based projects
`

My environment configuration is as follows:
> gcc/g++ version 7.5.0
> cuda version 11.1
> pytoch 1.10.1 and 2.0.1
> Python 3.8
> Ubuntu 18.04

**Comment by MenglinQiu** [comment]
Thank you for your answer. I found out the reason is that new symbolic links were not created when gcc/g++ was updated. (But the strange thing is that other C++ projects compile smoothly without being affected.)
